-- Seed de exercícios curados em português brasileiro (base inicial; wger importado depois)
insert into public.exercises (name, movement_pattern, primary_muscles, secondary_muscles, load_type, unilateral, source) values
('Agachamento livre', 'squat', '{quads,glutes}', '{core,hamstrings}', 'barbell', false, 'custom'),
('Agachamento frontal', 'squat', '{quads}', '{glutes,core}', 'barbell', false, 'custom'),
('Agachamento no Smith', 'squat', '{quads,glutes}', '{hamstrings}', 'machine', false, 'custom'),
('Agachamento hack', 'squat', '{quads,glutes}', '{core}', 'machine', false, 'custom'),
('Leg press', 'squat', '{quads,glutes}', '{hamstrings}', 'machine', false, 'custom'),
('Agachamento goblet', 'squat', '{quads,glutes}', '{core}', 'dumbbell', false, 'custom'),
('Agachamento sissy', 'squat', '{quads}', '{core}', 'bodyweight', false, 'custom'),
('Levantamento terra', 'hinge', '{glutes,hamstrings}', '{back,core}', 'barbell', false, 'custom'),
('Levantamento terra sumô', 'hinge', '{glutes,hamstrings}', '{back,core}', 'barbell', false, 'custom'),
('Stiff com barra', 'hinge', '{hamstrings,glutes}', '{back}', 'barbell', false, 'custom'),
('Stiff com halteres', 'hinge', '{hamstrings,glutes}', '{back}', 'dumbbell', false, 'custom'),
('Good morning', 'hinge', '{hamstrings,glutes}', '{back,core}', 'barbell', false, 'custom'),
('Hip thrust', 'hinge', '{glutes}', '{hamstrings,back}', 'barbell', false, 'custom'),
('Hip thrust com haltere', 'hinge', '{glutes}', '{hamstrings}', 'dumbbell', false, 'custom'),
('Kettlebell swing', 'hinge', '{glutes,hamstrings}', '{back,core}', 'kettlebell', false, 'custom'),
('Supino reto', 'push_h', '{chest,triceps}', '{shoulders}', 'barbell', false, 'custom'),
('Supino reto com halteres', 'push_h', '{chest,triceps}', '{shoulders}', 'dumbbell', false, 'custom'),
('Supino no Smith', 'push_h', '{chest,triceps}', '{shoulders}', 'machine', false, 'custom'),
('Supino inclinado', 'push_h', '{chest,shoulders}', '{triceps}', 'barbell', false, 'custom'),
('Supino inclinado com halteres', 'push_h', '{chest,shoulders}', '{triceps}', 'dumbbell', false, 'custom'),
('Flexão de braço', 'push_h', '{chest,triceps}', '{shoulders,core}', 'bodyweight', false, 'custom'),
('Voador (peck deck)', 'push_h', '{chest}', '{shoulders}', 'machine', false, 'custom'),
('Crucifixo com halteres', 'push_h', '{chest}', '{shoulders}', 'dumbbell', false, 'custom'),
('Crucifixo no cabo (crossover)', 'push_h', '{chest}', '{shoulders}', 'cable', false, 'custom'),
('Desenvolvimento militar', 'push_v', '{shoulders,triceps}', '{chest,core}', 'barbell', false, 'custom'),
('Desenvolvimento com halteres', 'push_v', '{shoulders,triceps}', '{chest}', 'dumbbell', false, 'custom'),
('Desenvolvimento na máquina', 'push_v', '{shoulders,triceps}', '{chest}', 'machine', false, 'custom'),
('Push press', 'push_v', '{shoulders,triceps}', '{quads,core}', 'barbell', false, 'custom'),
('Flexão pike', 'push_v', '{shoulders}', '{triceps,core}', 'bodyweight', false, 'custom'),
('Remada curvada', 'pull_h', '{back,biceps}', '{core}', 'barbell', false, 'custom'),
('Remada cavalinho', 'pull_h', '{back,biceps}', '{core}', 'barbell', false, 'custom'),
('Remada baixa no cabo', 'pull_h', '{back,biceps}', '{core}', 'cable', false, 'custom'),
('Remada na máquina', 'pull_h', '{back,biceps}', '{core}', 'machine', false, 'custom'),
('Remada unilateral com haltere (serrote)', 'pull_h', '{back,biceps}', '{core}', 'dumbbell', true, 'custom'),
('Barra fixa', 'pull_v', '{back,biceps}', '{core}', 'bodyweight', false, 'custom'),
('Puxada frontal', 'pull_v', '{back,biceps}', '{core}', 'cable', false, 'custom'),
('Puxada aberta', 'pull_v', '{back,biceps}', '{core}', 'cable', false, 'custom'),
('Puxada com triângulo', 'pull_v', '{back,biceps}', '{core}', 'cable', false, 'custom'),
('Pulldown com braços estendidos', 'pull_v', '{back}', '{triceps,core}', 'cable', false, 'custom'),
('Afundo', 'lunge', '{quads,glutes}', '{hamstrings,core}', 'bodyweight', true, 'custom'),
('Afundo com halteres', 'lunge', '{quads,glutes}', '{hamstrings,core}', 'dumbbell', true, 'custom'),
('Agachamento búlgaro', 'lunge', '{quads,glutes}', '{hamstrings}', 'dumbbell', true, 'custom'),
('Afundo reverso', 'lunge', '{glutes,quads}', '{hamstrings}', 'bodyweight', true, 'custom'),
('Passada (afundo caminhando)', 'lunge', '{quads,glutes}', '{hamstrings}', 'dumbbell', true, 'custom'),
('Subida no banco (step-up)', 'lunge', '{quads,glutes}', '{hamstrings,core}', 'dumbbell', true, 'custom'),
('Caminhada do fazendeiro com halteres', 'carry', '{forearms,core}', '{back}', 'dumbbell', false, 'custom'),
('Caminhada do fazendeiro com kettlebell', 'carry', '{forearms,core}', '{back}', 'kettlebell', false, 'custom'),
('Prancha', 'core', '{core}', '{shoulders}', 'bodyweight', false, 'custom'),
('Prancha lateral', 'core', '{core}', '{shoulders}', 'bodyweight', true, 'custom'),
('Abdominal na máquina', 'core', '{core}', '{}', 'machine', false, 'custom'),
('Elevação de pernas suspenso', 'core', '{core}', '{forearms}', 'bodyweight', false, 'custom'),
('Abdominal no cabo (crunch ajoelhado)', 'core', '{core}', '{}', 'cable', false, 'custom'),
('Rosca direta', 'isolation', '{biceps}', '{forearms}', 'barbell', false, 'custom'),
('Rosca alternada com halteres', 'isolation', '{biceps}', '{forearms}', 'dumbbell', false, 'custom'),
('Rosca Scott', 'isolation', '{biceps}', '{forearms}', 'barbell', false, 'custom'),
('Rosca martelo', 'isolation', '{biceps,forearms}', '{}', 'dumbbell', false, 'custom'),
('Rosca no cabo', 'isolation', '{biceps}', '{forearms}', 'cable', false, 'custom'),
('Tríceps testa', 'isolation', '{triceps}', '{}', 'barbell', false, 'custom'),
('Tríceps na polia (barra)', 'isolation', '{triceps}', '{}', 'cable', false, 'custom'),
('Tríceps corda', 'isolation', '{triceps}', '{}', 'cable', false, 'custom'),
('Tríceps francês', 'isolation', '{triceps}', '{}', 'dumbbell', false, 'custom'),
('Mergulho no banco', 'isolation', '{triceps}', '{chest,shoulders}', 'bodyweight', false, 'custom'),
('Elevação lateral', 'isolation', '{shoulders}', '{}', 'dumbbell', false, 'custom'),
('Elevação frontal', 'isolation', '{shoulders}', '{}', 'dumbbell', false, 'custom'),
('Crucifixo inverso (posterior de ombro)', 'isolation', '{shoulders}', '{back}', 'dumbbell', false, 'custom'),
('Face pull', 'isolation', '{shoulders}', '{back}', 'cable', false, 'custom'),
('Encolhimento de ombros', 'isolation', '{shoulders}', '{forearms}', 'barbell', false, 'custom'),
('Mesa flexora', 'isolation', '{hamstrings}', '{}', 'machine', false, 'custom'),
('Cadeira flexora', 'isolation', '{hamstrings}', '{}', 'machine', false, 'custom'),
('Cadeira extensora', 'isolation', '{quads}', '{}', 'machine', false, 'custom'),
('Cadeira adutora', 'isolation', '{glutes}', '{}', 'machine', false, 'custom'),
('Cadeira abdutora', 'isolation', '{glutes}', '{}', 'machine', false, 'custom'),
('Panturrilha em pé', 'isolation', '{calves}', '{}', 'machine', false, 'custom'),
('Panturrilha sentado', 'isolation', '{calves}', '{}', 'machine', false, 'custom'),
('Panturrilha no leg press', 'isolation', '{calves}', '{}', 'machine', false, 'custom'),
('Rosca de punho', 'isolation', '{forearms}', '{}', 'barbell', false, 'custom'),
('Glúteo no cabo (coice)', 'isolation', '{glutes}', '{hamstrings}', 'cable', true, 'custom'),
('Elevação pélvica unilateral', 'isolation', '{glutes}', '{hamstrings,core}', 'bodyweight', true, 'custom');
